package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private String login;
     private int idCont;
     private String password;

    public Admin() {
    }

	
    public Admin(String login, int idCont) {
        this.login = login;
        this.idCont = idCont;
    }
    public Admin(String login, int idCont, String password) {
       this.login = login;
       this.idCont = idCont;
       this.password = password;
    }
   
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public int getIdCont() {
        return this.idCont;
    }
    
    public void setIdCont(int idCont) {
        this.idCont = idCont;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


