package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1



/**
 * AntecedentChirurgical generated by hbm2java
 */
public class AntecedentChirurgical  implements java.io.Serializable {


     private Integer idCh;
     private String nomOp;

    public AntecedentChirurgical() {
    }

    public AntecedentChirurgical(String nomOp) {
       this.nomOp = nomOp;
    }
   
    public Integer getIdCh() {
        return this.idCh;
    }
    
    public void setIdCh(Integer idCh) {
        this.idCh = idCh;
    }
    public String getNomOp() {
        return this.nomOp;
    }
    
    public void setNomOp(String nomOp) {
        this.nomOp = nomOp;
    }




}


