package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1



/**
 * Avis generated by hbm2java
 */
public class Avis  implements java.io.Serializable {


     private Integer idAv;
     private Integer niveau;
     private String descriptionAv;

    public Avis() {
    }

    public Avis(Integer niveau, String descriptionAv) {
       this.niveau = niveau;
       this.descriptionAv = descriptionAv;
    }
   
    public Integer getIdAv() {
        return this.idAv;
    }
    
    public void setIdAv(Integer idAv) {
        this.idAv = idAv;
    }
    public Integer getNiveau() {
        return this.niveau;
    }
    
    public void setNiveau(Integer niveau) {
        this.niveau = niveau;
    }
    public String getDescriptionAv() {
        return this.descriptionAv;
    }
    
    public void setDescriptionAv(String descriptionAv) {
        this.descriptionAv = descriptionAv;
    }




}


