package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1



/**
 * Cabinet generated by hbm2java
 */
public class Cabinet  implements java.io.Serializable {


     private Integer idCab;
     private int idProf;
     private int idSec;
     private String adresseCab;
     private String gouvernorat;
     private String delegation;
     private Integer telFixe;
     private String descriptionCab;
     private Float prixVisite;
     private Boolean paimentCarteB;

    public Cabinet() {
    }

	
    public Cabinet(int idProf, int idSec) {
        this.idProf = idProf;
        this.idSec = idSec;
    }
    public Cabinet(int idProf, int idSec, String adresseCab, String gouvernorat, String delegation, Integer telFixe, String descriptionCab, Float prixVisite, Boolean paimentCarteB) {
       this.idProf = idProf;
       this.idSec = idSec;
       this.adresseCab = adresseCab;
       this.gouvernorat = gouvernorat;
       this.delegation = delegation;
       this.telFixe = telFixe;
       this.descriptionCab = descriptionCab;
       this.prixVisite = prixVisite;
       this.paimentCarteB = paimentCarteB;
    }
   
    public Integer getIdCab() {
        return this.idCab;
    }
    
    public void setIdCab(Integer idCab) {
        this.idCab = idCab;
    }
    public int getIdProf() {
        return this.idProf;
    }
    
    public void setIdProf(int idProf) {
        this.idProf = idProf;
    }
   
    public int getIdSec() {
        return this.idSec;
    }
    
    public void setIdSec(int idSec) {
        this.idSec = idSec;
    }
    public String getAdresseCab() {
        return this.adresseCab;
    }
    
    public void setAdresseCab(String adresseCab) {
        this.adresseCab = adresseCab;
    }
    public String getGouvernorat() {
        return this.gouvernorat;
    }
    
    public void setGouvernorat(String gouvernorat) {
        this.gouvernorat = gouvernorat;
    }
    public String getDelegation() {
        return this.delegation;
    }
    
    public void setDelegation(String delegation) {
        this.delegation = delegation;
    }
    public Integer getTelFixe() {
        return this.telFixe;
    }
    
    public void setTelFixe(Integer telFixe) {
        this.telFixe = telFixe;
    }
    public String getDescriptionCab() {
        return this.descriptionCab;
    }
    
    public void setDescriptionCab(String descriptionCab) {
        this.descriptionCab = descriptionCab;
    }
    public Float getPrixVisite() {
        return this.prixVisite;
    }
    
    public void setPrixVisite(Float prixVisite) {
        this.prixVisite = prixVisite;
    }
    public Boolean getPaimentCarteB() {
        return this.paimentCarteB;
    }
    
    public void setPaimentCarteB(Boolean paimentCarteB) {
        this.paimentCarteB = paimentCarteB;
    }




}


