package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Consultation generated by hbm2java
 */
public class Consultation  implements java.io.Serializable {


     private Integer idCon;
     private int idPat;
     private int idProf;
     private int idRend;
     private Date dateCon;
     private Date heureCon;
     private String ordonnance;

    public Consultation() {
    }

	
    public Consultation(int idPat, int idProf, int idRend) {
        this.idPat = idPat;
        this.idProf = idProf;
        this.idRend = idRend;
    }
    public Consultation(int idPat, int idProf, int idRend, Date dateCon, Date heureCon, String ordonnance) {
       this.idPat = idPat;
       this.idProf = idProf;
       this.idRend = idRend;
       this.dateCon = dateCon;
       this.heureCon = heureCon;
       this.ordonnance = ordonnance;
    }
   
    public Integer getIdCon() {
        return this.idCon;
    }
    
    public void setIdCon(Integer idCon) {
        this.idCon = idCon;
    }
    public int getIdPat() {
        return this.idPat;
    }
    
    public void setIdPat(int idPat) {
        this.idPat = idPat;
    }
    public int getIdProf() {
        return this.idProf;
    }
    
    public void setIdProf(int idProf) {
        this.idProf = idProf;
    }
    public int getIdRend() {
        return this.idRend;
    }
    
    public void setIdRend(int idRend) {
        this.idRend = idRend;
    }
    public Date getDateCon() {
        return this.dateCon;
    }
    
    public void setDateCon(Date dateCon) {
        this.dateCon = dateCon;
    }
    public Date getHeureCon() {
        return this.heureCon;
    }
    
    public void setHeureCon(Date heureCon) {
        this.heureCon = heureCon;
    }
    public String getOrdonnance() {
        return this.ordonnance;
    }
    
    public void setOrdonnance(String ordonnance) {
        this.ordonnance = ordonnance;
    }




}


