package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private Integer idCont;
     private String messageCont;
     private Date dateCont;
     private Integer etatCont;

    public Contact() {
    }

    public Contact(String messageCont, Date dateCont, Integer etatCont) {
       this.messageCont = messageCont;
       this.dateCont = dateCont;
       this.etatCont = etatCont;
    }
   
    public Integer getIdCont() {
        return this.idCont;
    }
    
    public void setIdCont(Integer idCont) {
        this.idCont = idCont;
    }
    public String getMessageCont() {
        return this.messageCont;
    }
    
    public void setMessageCont(String messageCont) {
        this.messageCont = messageCont;
    }
    public Date getDateCont() {
        return this.dateCont;
    }
    
    public void setDateCont(Date dateCont) {
        this.dateCont = dateCont;
    }
    public Integer getEtatCont() {
        return this.etatCont;
    }
    
    public void setEtatCont(Integer etatCont) {
        this.etatCont = etatCont;
    }




}


