package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Horaire generated by hbm2java
 */
public class Horaire  implements java.io.Serializable {


     private Integer idH;
     private String jour;
     private Date HMU;
     private Date HMD;
     private Date HSU;
     private Date HSD;
     private int idCab;

    public Horaire() {
    }

    public Horaire(String jour, Date HMU, Date HMD, Date HSU, Date HSD, int idCab) {
       this.jour = jour;
       this.HMU = HMU;
       this.HMD = HMD;
       this.HSU = HSU;
       this.HSD = HSD;
       this.idCab = idCab;
    }

    public int getIdCab() {
        return idCab;
    }

    public void setIdCab(int idCab) {
        this.idCab = idCab;
    }
   
    public Integer getIdH() {
        return this.idH;
    }
    
    public void setIdH(Integer idH) {
        this.idH = idH;
    }
    public String getJour() {
        return this.jour;
    }
    
    public void setJour(String jour) {
        this.jour = jour;
    }
    public Date getHMU() {
        return this.HMU;
    }
    
    public void setHMU(Date HMU) {
        this.HMU = HMU;
    }
    public Date getHMD() {
        return this.HMD;
    }
    
    public void setHMD(Date HMD) {
        this.HMD = HMD;
    }
    public Date getHSU() {
        return this.HSU;
    }
    
    public void setHSU(Date HSU) {
        this.HSU = HSU;
    }
    public Date getHSD() {
        return this.HSD;
    }
    
    public void setHSD(Date HSD) {
        this.HSD = HSD;
    }




}


