package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1



/**
 * Maladie generated by hbm2java
 */
public class Maladie  implements java.io.Serializable {


     private Integer idM;
     private String typeM;
     private String nomM;

    public Maladie() {
    }

    public Maladie(String typeM, String nomM) {
       this.typeM = typeM;
       this.nomM = nomM;
    }
   
    public Integer getIdM() {
        return this.idM;
    }
    
    public void setIdM(Integer idM) {
        this.idM = idM;
    }
    public String getTypeM() {
        return this.typeM;
    }
    
    public void setTypeM(String typeM) {
        this.typeM = typeM;
    }
    public String getNomM() {
        return this.nomM;
    }
    
    public void setNomM(String nomM) {
        this.nomM = nomM;
    }




}


