package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Medicament generated by hbm2java
 */
public class Medicament  implements java.io.Serializable {


     private Integer idMed;
     private String nomMed;
     private String formeMed;
     private String classeTherp;
     private String sousClasseTherp;
     private Date dateValidite;
     private byte[] photoMed;
     private Integer quantite;
     private int idPat;

    public int getIdPat() {
        return idPat;
    }

    public void setIdPat(int idPat) {
        this.idPat = idPat;
    }

    public Medicament() {
    }

    public Medicament(String nomMed, String formeMed, String classeTherp, String sousClasseTherp, Date dateValidite, byte[] photoMed, Integer quantite) {
       this.nomMed = nomMed;
       this.formeMed = formeMed;
       this.classeTherp = classeTherp;
       this.sousClasseTherp = sousClasseTherp;
       this.dateValidite = dateValidite;
       this.photoMed = photoMed;
       this.quantite = quantite;
    }
   
    public Integer getIdMed() {
        return this.idMed;
    }
    
    public void setIdMed(Integer idMed) {
        this.idMed = idMed;
    }
    public String getNomMed() {
        return this.nomMed;
    }
    
    public void setNomMed(String nomMed) {
        this.nomMed = nomMed;
    }
    public String getFormeMed() {
        return this.formeMed;
    }
    
    public void setFormeMed(String formeMed) {
        this.formeMed = formeMed;
    }
    public String getClasseTherp() {
        return this.classeTherp;
    }
    
    public void setClasseTherp(String classeTherp) {
        this.classeTherp = classeTherp;
    }
    public String getSousClasseTherp() {
        return this.sousClasseTherp;
    }
    
    public void setSousClasseTherp(String sousClasseTherp) {
        this.sousClasseTherp = sousClasseTherp;
    }
    public Date getDateValidite() {
        return this.dateValidite;
    }
    
    public void setDateValidite(Date dateValidite) {
        this.dateValidite = dateValidite;
    }
    public byte[] getPhotoMed() {
        return this.photoMed;
    }
    
    public void setPhotoMed(byte[] photoMed) {
        this.photoMed = photoMed;
    }
    public Integer getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(Integer quantite) {
        this.quantite = quantite;
    }
}


