package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1



/**
 * PatientMId generated by hbm2java
 */
public class PatientMId  implements java.io.Serializable {


     private int idPat;
     private int idM;

    public PatientMId() {
    }

    public PatientMId(int idPat, int idM) {
       this.idPat = idPat;
       this.idM = idM;
    }
   
    public int getIdPat() {
        return this.idPat;
    }
    
    public void setIdPat(int idPat) {
        this.idPat = idPat;
    }
    public int getIdM() {
        return this.idM;
    }
    
    public void setIdM(int idM) {
        this.idM = idM;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatientMId) ) return false;
		 PatientMId castOther = ( PatientMId ) other; 
         
		 return (this.getIdPat()==castOther.getIdPat())
 && (this.getIdM()==castOther.getIdM());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPat();
         result = 37 * result + this.getIdM();
         return result;
   }   


}


