package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1



/**
 * PatientAlId generated by hbm2java
 */
public class PatientAlId  implements java.io.Serializable {


     private int idPat;
     private int idAl;

    public PatientAlId() {
    }

    public PatientAlId(int idPat, int idAl) {
       this.idPat = idPat;
       this.idAl = idAl;
    }
   
    public int getIdPat() {
        return this.idPat;
    }
    
    public void setIdPat(int idPat) {
        this.idPat = idPat;
    }
    public int getIdAl() {
        return this.idAl;
    }
    
    public void setIdAl(int idAl) {
        this.idAl = idAl;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatientAlId) ) return false;
		 PatientAlId castOther = ( PatientAlId ) other; 
         
		 return (this.getIdPat()==castOther.getIdPat())
 && (this.getIdAl()==castOther.getIdAl());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPat();
         result = 37 * result + this.getIdAl();
         return result;
   }   


}


