package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1



/**
 * PatientChId generated by hbm2java
 */
public class PatientChId  implements java.io.Serializable {


     private int idPat;
     private int idCh;

    public PatientChId() {
    }

    public PatientChId(int idPat, int idCh) {
       this.idPat = idPat;
       this.idCh = idCh;
    }
   
    public int getIdPat() {
        return this.idPat;
    }
    
    public void setIdPat(int idPat) {
        this.idPat = idPat;
    }
    public int getIdCh() {
        return this.idCh;
    }
    
    public void setIdCh(int idCh) {
        this.idCh = idCh;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatientChId) ) return false;
		 PatientChId castOther = ( PatientChId ) other; 
         
		 return (this.getIdPat()==castOther.getIdPat())
 && (this.getIdCh()==castOther.getIdCh());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPat();
         result = 37 * result + this.getIdCh();
         return result;
   }   


}


