package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PatientCh generated by hbm2java
 */
public class PatientCh  implements java.io.Serializable {


     private PatientChId id;
     private String raison;
     private Date dateOp;
     private String local;

    public PatientCh() {
    }

	
    public PatientCh(PatientChId id) {
        this.id = id;
    }
    public PatientCh(PatientChId id, String raison, Date dateOp, String local) {
       this.id = id;
       this.raison = raison;
       this.dateOp = dateOp;
       this.local = local;
    }
   
    public PatientChId getId() {
        return this.id;
    }
    
    public void setId(PatientChId id) {
        this.id = id;
    }
    public String getRaison() {
        return this.raison;
    }
    
    public void setRaison(String raison) {
        this.raison = raison;
    }
    public Date getDateOp() {
        return this.dateOp;
    }
    
    public void setDateOp(Date dateOp) {
        this.dateOp = dateOp;
    }
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }




}


