package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PatientM generated by hbm2java
 */
public class PatientM  implements java.io.Serializable {


     private PatientMId id;
     private Date dateDM;
     private Date dateFM;
     private String traitement;
     private Boolean arretTrav;

    public PatientM() {
    }

	
    public PatientM(PatientMId id) {
        this.id = id;
    }
    public PatientM(PatientMId id, Date dateDM, Date dateFM, String traitement, Boolean arretTrav) {
       this.id = id;
       this.dateDM = dateDM;
       this.dateFM = dateFM;
       this.traitement = traitement;
       this.arretTrav = arretTrav;
    }
   
    public PatientMId getId() {
        return this.id;
    }
    
    public void setId(PatientMId id) {
        this.id = id;
    }
    public Date getDateDM() {
        return this.dateDM;
    }
    
    public void setDateDM(Date dateDM) {
        this.dateDM = dateDM;
    }
    public Date getDateFM() {
        return this.dateFM;
    }
    
    public void setDateFM(Date dateFM) {
        this.dateFM = dateFM;
    }
    public String getTraitement() {
        return this.traitement;
    }
    
    public void setTraitement(String traitement) {
        this.traitement = traitement;
    }
    public Boolean getArretTrav() {
        return this.arretTrav;
    }
    
    public void setArretTrav(Boolean arretTrav) {
        this.arretTrav = arretTrav;
    }




}


