package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProfessionnelSante generated by hbm2java
 */
public class ProfessionnelSante  implements java.io.Serializable {


     private Integer idProf;
     private String nomProf;
     private String prenomProf;
     private String loginProf;
     private String passwordProf;
     private Date dateNaisProf;
     private String adresseProf;
     private String emailProf;
     private Integer telMob;
     private Boolean etatProf;
     private String genreProf;
     private String diplome;
     private byte[] photoIdentite;
     private Boolean visiteADomicile;
     private int idSpec;

    public ProfessionnelSante() {
    }

    public ProfessionnelSante(String nomProf, String prenomProf, String loginProf, String passwordProf, Date dateNaisProf, String adresseProf, String emailProf, Integer telMob, Boolean etatProf, String genreProf, String diplome, byte[] photoIdentite, Boolean visiteADomicile, int id_spec) {
       this.nomProf = nomProf;
       this.prenomProf = prenomProf;
       this.loginProf = loginProf;
       this.passwordProf = passwordProf;
       this.dateNaisProf = dateNaisProf;
       this.adresseProf = adresseProf;
       this.emailProf = emailProf;
       this.telMob = telMob;
       this.etatProf = etatProf;
       this.genreProf = genreProf;
       this.diplome = diplome;
       this.photoIdentite = photoIdentite;
       this.visiteADomicile = visiteADomicile;
       this.idSpec = id_spec;
    }

    public int getIdSpec() {
        return idSpec;
    }

    public void setIdSpec(int idSpec) {
        this.idSpec = idSpec;
    }
   
    public Integer getIdProf() {
        return this.idProf;
    }
    
    public void setIdProf(Integer idProf) {
        this.idProf = idProf;
    }
   
    public String getNomProf() {
        return this.nomProf;
    }
    
    public void setNomProf(String nomProf) {
        this.nomProf = nomProf;
    }
    public String getPrenomProf() {
        return this.prenomProf;
    }
    
    public void setPrenomProf(String prenomProf) {
        this.prenomProf = prenomProf;
    }
    public String getLoginProf() {
        return this.loginProf;
    }
    
    public void setLoginProf(String loginProf) {
        this.loginProf = loginProf;
    }
    public String getPasswordProf() {
        return this.passwordProf;
    }
    
    public void setPasswordProf(String passwordProf) {
        this.passwordProf = passwordProf;
    }
    public Date getDateNaisProf() {
        return this.dateNaisProf;
    }
    
    public void setDateNaisProf(Date dateNaisProf) {
        this.dateNaisProf = dateNaisProf;
    }
    public String getAdresseProf() {
        return this.adresseProf;
    }
    
    public void setAdresseProf(String adresseProf) {
        this.adresseProf = adresseProf;
    }
    public String getEmailProf() {
        return this.emailProf;
    }
    
    public void setEmailProf(String emailProf) {
        this.emailProf = emailProf;
    }
    public Integer getTelMob() {
        return this.telMob;
    }
    
    public void setTelMob(Integer telMob) {
        this.telMob = telMob;
    }
    public Boolean getEtatProf() {
        return this.etatProf;
    }
    
    public void setEtatProf(Boolean etatProf) {
        this.etatProf = etatProf;
    }
    
    public String getGenreProf() {
        return this.genreProf;
    }
    
    public void setGenreProf(String genreProf) {
        this.genreProf = genreProf;
    }
    public String getDiplome() {
        return this.diplome;
    }
    
    public void setDiplome(String diplome) {
        this.diplome = diplome;
    }
    public byte[] getPhotoIdentite() {
        return this.photoIdentite;
    }
    
    public void setPhotoIdentite(byte[] photoIdentite) {
        this.photoIdentite = photoIdentite;
    }
    public Boolean getVisiteADomicile() {
        return this.visiteADomicile;
    }
    
    public void setVisiteADomicile(Boolean visiteADomicile) {
        this.visiteADomicile = visiteADomicile;
    }




}


