package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RendezVous generated by hbm2java
 */
public class RendezVous  implements java.io.Serializable {


     private Integer idRend;
     private Date dateRend;
     private Date heureRend;

    public RendezVous() {
    }

    public RendezVous(Date dateRend, Date heureRend) {
       this.dateRend = dateRend;
       this.heureRend = heureRend;
    }
   
    public Integer getIdRend() {
        return this.idRend;
    }
    
    public void setIdRend(Integer idRend) {
        this.idRend = idRend;
    }
    public Date getDateRend() {
        return this.dateRend;
    }
    
    public void setDateRend(Date dateRend) {
        this.dateRend = dateRend;
    }
    public Date getHeureRend() {
        return this.heureRend;
    }
    
    public void setHeureRend(Date heureRend) {
        this.heureRend = heureRend;
    }




}


