package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1



/**
 * Reponse generated by hbm2java
 */
public class Reponse  implements java.io.Serializable {


     private Integer idR;
     private int idQ;
     private int idProf;

    public int getIdQ() {
        return idQ;
    }

    public void setIdQ(int idQ) {
        this.idQ = idQ;
    }

    public int getIdProf() {
        return idProf;
    }

    public void setIdProf(int idProf) {
        this.idProf = idProf;
    }
     private String reponse;

    public Reponse() {
    }

    public Reponse(String reponse) {
       this.reponse = reponse;
    }
   
    public Integer getIdR() {
        return this.idR;
    }
    
    public void setIdR(Integer idR) {
        this.idR = idR;
    }
    public String getReponse() {
        return this.reponse;
    }
    
    public void setReponse(String reponse) {
        this.reponse = reponse;
    }




}


