package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1



/**
 * Soin generated by hbm2java
 */
public class Soin  implements java.io.Serializable {


     private Integer idSoin;
     private String soin;
     private int idCab;

    public int getIdCab() {
        return idCab;
    }

    public void setIdCab(int idCab) {
        this.idCab = idCab;
    }
     private Float prix;

    public Soin() {
    }

    public Soin(String soin, Float prix) {
       this.soin = soin;
       this.prix = prix;
    }
   
    public Integer getIdSoin() {
        return this.idSoin;
    }
    
    public void setIdSoin(Integer idSoin) {
        this.idSoin = idSoin;
    }
    public String getSoin() {
        return this.soin;
    }
    
    public void setSoin(String soin) {
        this.soin = soin;
    }
    public Float getPrix() {
        return this.prix;
    }
    
    public void setPrix(Float prix) {
        this.prix = prix;
    }




}


