package com.e_medecine.entities;
// Generated 10 avr. 2020 06:38:05 by Hibernate Tools 4.3.1



/**
 * Specialite generated by hbm2java
 */
public class Specialite  implements java.io.Serializable {


     private Integer idSpec;
     private String nomSpec;

    public Specialite() {
    }
    public Specialite(String nomSpec) {
       this.nomSpec = nomSpec;
    }
   
    public Integer getIdSpec() {
        return this.idSpec;
    }
    
    public void setIdSpec(Integer idSpec) {
        this.idSpec = idSpec;
    }
    public String getNomSpec() {
        return this.nomSpec;
    }
    
    public void setNomSpec(String nomSpec) {
        this.nomSpec = nomSpec;
    }




}


